## Author

- **Name:** Maxwell Yang
- **Email:** my37@illinois.edu

## Purpose

The purpose of this application is to view the stats of every NBA franchise from 1980-2019 in a table or in a trendline. The landscape and gameplay has changed a lot from 1980-2019, so being able to visualize the changes and see the difference in playstyles year by year is very beneficial for anyone doing analysis on the nba.

## Data

Each row represents the data of a team in a given year  
* Rk (Rank) - Rank of that team at the end of the season   
* MP (Minutes Played)- Number of minutes played by all players per game   
* FG (Field Goals)- Number of baskets scored per game   
* FGA (Field Goals Attempted) - Number of baskets attempted per game   
* FG% (Field Goal Percent)- Percent of attempts that are scored per game   
* 3P (Three-Pointers)- Number of three-pointers score per game   
* 3PA (Three-Pointers Attempted)- Number of three-pointers attempted per game   
* 3P% (Three-Pointer Percent)- Percent of three-point attempts that are scored per game   
* 2P (Two-Pointers)- Number of two-pointers score per game   
* 2PA (Two-Pointers Attempted)- Number of two-pointers attempted per game   
* 2P% (Two-Pointer Percent)- Percent of two-point attempts that are scored per game   
* FT (Free Throws)- Free throws made per game   
* FTA (Free Throws Attempted)- Number of free throws made per game   
* FT% (Free Throw Percent)- Percent of free throw attempts that are scored per game   
* ORB (Offensive Rebounds)- Number of offensive rebounds per game   
* DRB (Defensive Rebounds)- Number of defensive rebounds per game   
* TRB (Total Rebounds)- Number of total rebounds per game   
* AST (Total Assists)- Number of assists per game  
* STL (Total Steals)- Number of steals per game   
* BLK (Total Blocks)- Number of blocks per game   
* TOV (Turnovers)- Number of turnovers per game   
* PF (Personal Fouls)- Number of personal fouls per game by all players   
* PTS (Points)- Number of points per game   
* Year (Year)- The starting year of the NBA season the team played in (e.g. 2019-2020 represented is 2019) 

## References

-[Kaggle: Jon Pablo](https://www.kaggle.com/datasets/jpsdev/19802019-nba-team-stats?resource=download)
